# Generated by Django 3.2 on 2021-11-19 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_usercart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebill',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
    ]
