# Generated by Django 3.2 on 2021-11-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_usercart_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsercartSnapShort',
        ),
    ]
