# Generated by Django 3.2 on 2021-11-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_usercartsnapshort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartsnapshort',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
