# Generated by Django 3.2 on 2021-11-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_alter_usercartsnapshort_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbill',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
