# Generated by Django 3.2 on 2021-11-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_totalbill_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbill',
            name='product_identity',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='totalbill',
            name='token',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
