# Generated by Django 3.2 on 2021-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_auto_20211125_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbill',
            name='product_identity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
