# Generated by Django 3.2 on 2021-12-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('listing', '0002_auto_20211207_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='paid_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.paidpackageinfo'),
        ),
    ]
