# Generated by Django 3.2 on 2021-12-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_subdistrict_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdistrict',
            name='type',
            field=models.CharField(choices=[('Metro Cities', 'Metro Cities'), ('Sub-Metro Cities', 'Sub-Metro Cities'), ('Urban Municipalities', 'Urban Municipalities'), ('Rural Municipalities', 'Rural Municipalities')], max_length=25),
        ),
    ]
